# Generated by Django 6.0.1 on 2026-01-08 11:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('protocol', models.CharField(choices=[('modbus', 'Modbus TCP'), ('opcua', 'OPC UA')], max_length=20)),
                ('status', models.CharField(choices=[('disconnected', 'Disconnected'), ('connected', 'Connected'), ('error', 'Error')], default='disconnected', max_length=20)),
                ('latency_ms', models.IntegerField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True, default='')),
                ('auto_reconnect', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'app_devices',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Gateway',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('host', models.CharField(max_length=255)),
                ('adapter_id', models.CharField(blank=True, default='', max_length=255)),
                ('ports', models.JSONField(default=list)),
                ('status', models.CharField(default='unknown', max_length=50)),
                ('last_ping_ms', models.IntegerField(blank=True, null=True)),
                ('last_tcp_result', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'app_gateways',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Schema',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'app_schemas',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StorageTarget',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('provider', models.CharField(choices=[('sqlite', 'SQLite'), ('postgres', 'PostgreSQL'), ('mysql', 'MySQL'), ('mssql', 'SQL Server')], default='sqlite', max_length=20)),
                ('connection_string', models.TextField()),
                ('is_default', models.BooleanField(default=False)),
                ('status', models.CharField(default='unknown', max_length=50)),
                ('last_error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'app_storage_targets',
                'ordering': ['-is_default', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ModbusConfig',
            fields=[
                ('device', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='modbus_config', serialize=False, to='core_logger.device')),
                ('host', models.CharField(max_length=255)),
                ('port', models.IntegerField(default=502)),
                ('unit_id', models.IntegerField(default=1)),
                ('timeout_ms', models.IntegerField(default=3000)),
                ('retries', models.IntegerField(default=3)),
            ],
            options={
                'db_table': 'app_modbus_configs',
            },
        ),
        migrations.CreateModel(
            name='OpcuaConfig',
            fields=[
                ('device', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='opcua_config', serialize=False, to='core_logger.device')),
                ('endpoint', models.CharField(max_length=500)),
                ('auth_type', models.CharField(default='Anonymous', max_length=50)),
                ('username', models.CharField(blank=True, default='', max_length=255)),
                ('password', models.CharField(blank=True, default='', max_length=255)),
                ('security_policy', models.CharField(blank=True, default='', max_length=100)),
                ('security_mode', models.CharField(blank=True, default='', max_length=100)),
            ],
            options={
                'db_table': 'app_opcua_configs',
            },
        ),
        migrations.CreateModel(
            name='DeviceTable',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('migrated', 'Migrated'), ('error', 'Error')], default='pending', max_length=20)),
                ('mapping_health', models.CharField(choices=[('unmapped', 'Unmapped'), ('partial', 'Partially Mapped'), ('mapped', 'Fully Mapped')], default='unmapped', max_length=20)),
                ('last_migrated_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='device_tables', to='core_logger.device')),
                ('schema', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='device_tables', to='core_logger.schema')),
                ('storage_target', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='device_tables', to='core_logger.storagetarget')),
            ],
            options={
                'db_table': 'app_device_tables',
                'ordering': ['name'],
                'unique_together': {('name', 'storage_target')},
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('job_type', models.CharField(choices=[('continuous', 'Continuous'), ('trigger', 'Trigger')], default='continuous', max_length=20)),
                ('interval_ms', models.IntegerField(default=1000)),
                ('enabled', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('stopped', 'Stopped'), ('running', 'Running'), ('paused', 'Paused')], default='stopped', max_length=20)),
                ('batch_size', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tables', models.ManyToManyField(blank=True, related_name='jobs', to='core_logger.devicetable')),
            ],
            options={
                'db_table': 'app_jobs',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='JobRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('started_at', models.DateTimeField()),
                ('stopped_at', models.DateTimeField(blank=True, null=True)),
                ('duration_ms', models.IntegerField(blank=True, null=True)),
                ('rows_written', models.IntegerField(default=0)),
                ('reads_count', models.IntegerField(default=0)),
                ('read_errors', models.IntegerField(default=0)),
                ('write_errors', models.IntegerField(default=0)),
                ('avg_latency_ms', models.FloatField(blank=True, null=True)),
                ('p95_latency_ms', models.FloatField(blank=True, null=True)),
                ('error_log', models.JSONField(default=list)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='core_logger.job')),
            ],
            options={
                'db_table': 'app_job_runs',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='JobTrigger',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('field', models.CharField(max_length=255)),
                ('operator', models.CharField(choices=[('change', 'Change'), ('>', 'Greater than'), ('>=', 'Greater than or equal'), ('<', 'Less than'), ('<=', 'Less than or equal'), ('==', 'Equal'), ('!=', 'Not equal'), ('rising', 'Rising edge'), ('falling', 'Falling edge')], default='change', max_length=20)),
                ('value', models.FloatField(blank=True, null=True)),
                ('deadband', models.FloatField(default=0.0)),
                ('cooldown_ms', models.IntegerField(default=0)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='triggers', to='core_logger.job')),
            ],
            options={
                'db_table': 'app_job_triggers',
                'ordering': ['job', 'field'],
            },
        ),
        migrations.CreateModel(
            name='FieldMapping',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('field_key', models.CharField(max_length=255)),
                ('protocol', models.CharField(choices=[('modbus', 'Modbus TCP'), ('opcua', 'OPC UA')], max_length=20)),
                ('address', models.CharField(max_length=255)),
                ('data_type', models.CharField(choices=[('bool', 'Boolean'), ('int', 'Integer'), ('float', 'Float'), ('string', 'String')], default='float', max_length=20)),
                ('scale', models.FloatField(default=1.0)),
                ('deadband', models.FloatField(default=0.0)),
                ('byte_order', models.CharField(blank=True, choices=[('ABCD', 'Big-endian (ABCD)'), ('DCBA', 'Little-endian (DCBA)'), ('BADC', 'Mid-big (BADC)'), ('CDAB', 'Mid-little (CDAB)')], default='ABCD', max_length=10)),
                ('poll_interval_ms', models.IntegerField(blank=True, null=True)),
                ('device_table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mappings', to='core_logger.devicetable')),
            ],
            options={
                'db_table': 'app_field_mappings',
                'ordering': ['device_table', 'field_key'],
                'unique_together': {('device_table', 'field_key')},
            },
        ),
        migrations.CreateModel(
            name='SchemaField',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=255)),
                ('field_type', models.CharField(choices=[('bool', 'Boolean'), ('int', 'Integer'), ('float', 'Float'), ('string', 'String')], default='float', max_length=20)),
                ('unit', models.CharField(blank=True, default='', max_length=50)),
                ('scale', models.FloatField(default=1.0)),
                ('description', models.TextField(blank=True, default='')),
                ('schema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='core_logger.schema')),
            ],
            options={
                'db_table': 'app_schema_fields',
                'ordering': ['schema', 'key'],
                'unique_together': {('schema', 'key')},
            },
        ),
    ]
